[versions]
agp = "8.7.2"
kotlin = "1.9.24"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
material3 = "1.4.0-alpha04"
material3Version = "1.2.1"
datastorePreferences = "1.1.1"
recyclerview = "1.4.0-rc01"
preference = "1.2.1"
recyclerviewVersion = "1.3.2"
workRuntimeKtx = "2.10.0"
materialVersion = "1.2.1"
googleMaterial = "1.12.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.15.0" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3Version" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerviewVersion" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
com-google-android-material-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

